### ISSUE TITLE
Test::Stream has a fair bit of copy/paste code, reasons?

### ISSUE THREAD

**Issue by notbenh** [Test-More/Test-Stream#22]
Currently is, isnt, like, unlike are all copies (except for the op) it seems that they could all be built out of cmp_ok? Are there reasons for copies?

**Comment by exodist** [comment]
The main reason they are copies is because it is a very small amount of code to copy. We actually cannot save much by using cmp_ok under the hood since we still need to grab and release the context object in the wrapping sub. We could generate all these using a template and a loop, but it is simple enough that I did not bother.

**Comment by notbenh** [comment]
fair point, in testing it also screws up the events as now there is a cmp_ok event in there that is psudo-unexpected.
