### ISSUE TITLE
Reason for an empty default for update_state() in Test::Stream::Event base obj?

### ISSUE THREAD

**Issue by notbenh** [Test-More/Test-Stream#24]
shouldn't update_state() in the Event base object at least define some default action? or is state something that is not always expected to be updated? In the pod it might help to elaborate why this hook is here because currently I am not really sure why I would need to have a before wrapper around the object's pass to the formatter? Currently all the internal objects that use this base extend from it but it seems that there would be a desire to have some common action here... right?

**Comment by exodist** [comment]
Events like diag, note, and other non-result events have no need to modify state. Events like 'Ok' obviously need to update the state by bumping the test count and/or failure count.  BAIL-OUT events also need to mark the state as failing. Plan events set the plan in the state object.

So events can use this hook to update the state, but since many events do not actually touch the state the default is to do nothing.
