### ISSUE TITLE
5.10 "did it sigsegv" check does not work under taint mode

### ISSUE THREAD

**Issue by ribasushi** [Test-More/Test-Stream#28]
[This system() call](https://metacpan.org/source/Test::Stream::Capabilities#L68) does not work under taint mode, resulting in [failures like this](https://travis-ci.org/ribasushi/dbix-class/jobs/65766172#L5614) in various taint tests.

Additionally it is not entirely clear why are you using the single-arg version of system() as opposed to the list variant:
`system( $^X => -e => $the_entire_heredoc )`

Lastly the `checking for segfaults` line is extremely noisy, surely it can be elided...? In general the entire approach seems way too heavy (an extra fork/exec per test) for the task at hand...

/cc @kentfredric

**Comment by haarg** [comment]
Using -e with a long code block won't work well on Windows, so I think using a temp file is sensible.  It should still be using list form though.

**Comment by exodist** [comment]
i agree it is heavy handed. i would love it if someone could propose a better way. i will look at the suggestions here for foxing the current one. I am hoping we can find a better way to check this without forking and executing a script.

**Comment by exodist** [comment]
^ Would appreciate feedback.

**Comment by exodist** [comment]
ok, seems my untaint did not work, travis is telling me it failed. back to the drawing board.

**Comment by haarg** [comment]
Untainting is absolutely the wrong thing to do.

**Comment by exodist** [comment]
I was afraid it might be the wrong thing.

The 5.10.0 segv thing really seems to be one of those things where I am not sure Test-Simple/Stream should be responsible for it. I imagine that if you have an install where threading is broken that you already have a bad situation.

That said if a reasonable way to detect it is found I want to do so, and have Test-Simple work. But if this method is too heavy handed, and a better method cannot be found (and a way to check in taint mode can't be found) then I think I may have to stop trying to detect this and let it just segv so people know their perl is broken and it will be up to them to fix it, or force install.

So to  be clear:  I will be happy to work to support this, but only if there is a reasonable way. Fact is that some 5.10.0 installs are broken, and it is not test-*'s job to fix it.

**Comment by kentfredric** [comment]
The argument I'd use in favour of having some mechanism is so that when a
failure occurs, it is clear the failure is due to 5.10 thread failure, and
not some other weird bug. Having confusing segv's is not always something
an end user is able to easily diagnose.

As an alternative, you could disable the fork check under taint.

The odds of using a broken threaded perl *and* taint seems a much smaller
audience than those who merely have a broken threaded perl, or those who
use taint.

**Comment by haarg** [comment]
Clear out the relevant env variables rather than trying to untaint them.  And supply the perl you are calling with `-I$dir` parameters for everything in `@INC`.

**Comment by exodist** [comment]
I wonder if it would be better to do this check in the Makefile.PL and just make it a constant true or false in the module as-installed.

**Comment by kentfredric** [comment]
> I wonder if it would be better to do this check in the Makefile.PL and just make it a constant true or false in the module as-installed.

There would likely be a lot of implied consequences of that.

1. Complexity
2. Pure perl changing which perl it runs on doesn't update the check

**Comment by exodist** [comment]
I am thinking I will drop this 5.10 segv check. It is not a problem with Test::Stream or Test::Builder. The legacy code does not protect against it in any way so there is no backcompat I would be breaking. All other modules that run tests with threads will also have this problem.

I think that trying to solve it in Test-Stream is over-complicated, and not necessary.

**Comment by kentfredric** [comment]
Yeah. I kinda want something like that because I see the utility in making sure a user knows exactly why something goes "bang" when it does.

I'd like to suggest something like an install time check that when:

$Config{useithreads} = true && is a broken 5.10, exit N/A with a warning saying something like "Your perl threading implementation is broken and code can't run on it", and then instruct the user to perhaps hack Config.pm somehow to prevent ithreads from ever being used.

ie: by adding an entry like $Config{ithreads_broken} = 1,  and then checking for that entry.

This is all far too bold though. I just figure that seeing threads.pm can _never_ work on that platform, somebody should direct the perl install to prevent threads from ever running on that install in some way, in a manner that is not purely local to Test::Simple.

( Because it really affects more than Test::Simple )

**Comment by ribasushi** [comment]
This is a bit offtopic, but the ticket veered in that direction already. This entire dance of "detect this and that" is fundamentally misguided, because:

**The segfaulting threads problem is very rare, and does not affect actual deployed perls**

The observed behavior is due to `perl 5.10.0` being compiled with `gcc 4.9 (or later)` **only**. The real fix for this is to bisect the problem and to add a Devel::PatchPerl entry fixing it. The fact that `gcc 4.9` came out **7 years** after the affected `5.10.0` and **5 years** after the unaffected `5.10.1`, pretty much guarantees that the only affected systems are ones used for testing, and not deployed ones. As such work in the direction of a workaround is misguided at best, and likely actively harmful due to other interactions.

**Comment by kentfredric** [comment]
Indeed. This problem *might* be more visible under Test(::More|::Stream) though, because my expectation is those systems are going to be among the first to be upgraded, which at present might lead to a

"Freshly installed a perl 5.10.0 for some crazy reason, didn't notice it was broken somehow, upgraded TM/TS soon after because some dependency wanted an upgrade, and then something died in a shower of sparks, so foolish user thinks it *must be T:M/T:S's fault*".

After all, I believe that's the line of process that lead us to the discovery of the threads segv in the first place wasn't it?

I agree whole heartedly that it would be desirable for Devel::PatchPerl to be upgraded in some manner to avoid this problem entirely pre-emptively though. Its just a question for me of timescales and "will that happen, ever?"

**Comment by ribasushi** [comment]
> After all, I believe that's the line of process that lead us to the discovery of the threads segv in the first   place wasn't it?

The answer is *No* (and that's the thing). The reason the problem was "discovered" is because the problematic gcc came about around the same time @Exodist started working in earnest on testing things with earlier perls. The reason this has not been "noticed" by the vast majority of testers is because they either reuse previously built "oldperls", or because they use TravisCI which is locked on gcc4.7, and will likely remain so for years.

Does this clarify better why I keep repeating that the entire discussion is misplaced?

**Comment by ribasushi** [comment]
> "will that happen, ever?"

It will not happen until someone with access to the problematic gcc runs a bisect to figure out what caused things to start barfing. (I currently do not have easy access to such a gcc)
