### ISSUE TITLE
When $ENV{HARNESS_ACTIVE} is set, it should not change the TAP encoding

### ISSUE THREAD

**Issue by magnolia-k** [Test-More/Test-Stream#34]
When `$ENV{HARNESS_ACTIVE}` is set, the contents of the TAP is directly the input of the `TAP::Harness` module.

Rather than for human reading, when it is known that it becomes an input to another program (that is, when the `$ENV{HARNESS_ACTIVE}` is set),  than better to the TAP encoding for example, such as UTF-8 is ?

It also outputs a normal TAP when `$ENV{HARNESS_ACTIVE} is set to use the Test::Pretty, there are also modules to output the test results easy to read for more humans format when not set.

Support to facilitate making such a module is I think may be there.

`https://github.com/tokuhirom/Test-Pretty`

**Comment by exodist** [comment]
I am not sure I follow this, probably due to language barrier. Are you saying that you think set_encoding should be a no-op, as should the UTF8 plugin?

i would disagree with this. if you are producing utf8 output, you want the output handle to be utf8. it doesn't matter if the consumer is a program or a human. if you output utf8, or characters of any encoding, you want to make sure the handles are set to the correct encoding. if the harness cannot read utf8, then the test author should not produce utf8.

I do not think it is the testing tools job to change or refuse to change the encoding without the person writing the tests requesting it.

**Comment by exodist** [comment]
I believe the TS_FORMATTER environment variable is probably a sufficient fix to this?

**Comment by magnolia-k** [comment]
Certainly to have enabled the UTF8 plug-in, the output of the TAP is not in UTF-8, the person who writes the test is it confusing.

When a person to write a test is better to explicitly change the encoding to match the environment, I was convinced.

In order to change the output as in the Test::Pretty is, TS_FORMATTER is I think a very good solution.
