### ISSUE TITLE
Test::Stream::Event import method confusing

### ISSUE THREAD

**Issue by Leont** [Test-More/Test-Stream#60]
Currently, `Test::Stream::Event->import` does two things. It does the reasonable obvious thing of adding accessor method, and the not so obvious thing is that it makes `Test::Stream::Event` the base-class of the importing class.

Instead of 
~~~
use Test::Stream::Event(
    accessors => [qw/pass effective_pass name diag allow_bad_name/],
);
~~~
wouldn't something like
~~~
use Test::Stream::HashBase(
    base => 'Test::Stream::Event',
    accessors => [qw/pass effective_pass name diag allow_bad_name/],
);
~~~
be an awful lot clearer?

**Comment by exodist** [comment]
I debated this a lot when I was writing it, and almost changed it several times. Ultimately I went with this approach because writing a custom event type is a very specialized thing. Very few people will do it, and they better know what they are doing when they try. As a result reading the documentation of the Event package is essential, and it very clearly documents this interface.

I am open to being wrong here, so if you disagree please provide some arguments. I will change this if there are good reasons to do so.

**Comment by Leont** [comment]
Quite frankly, **I'm not sure if it's sane to extend the Event objects that way**, due to the waterbed theory of complexity.

Ultimately, Test::Stream is nothing more or less than a stream of Event objects. Various parts of that stream can do all sorts of things with these event objects. They're the language that all other components use to communicate to each other. Extensions introduce dialects, that can quickly lead to those components not understanding each other.

Having a decoupled design requires having a well defined base, IMO.

**Comment by exodist** [comment]
See https://github.com/Test-More/Test-Stream/pull/63 for a pull request on this.

**Comment by rjbs** [comment]
In light of #63 can this be closed?

**Comment by Leont** [comment]
Yes I think so

**Comment by rjbs** [comment]
We all agree this has been addressed and can be closed.  Closing this after weekly status update with @exodist.
