### ISSUE TITLE
Unclear relationship between Test::Stream and Test2::Suite

### ISSUE THREAD

**Issue by mlawren** [Test-More/Test-Stream#84]
I was following the development of Test::Stream via the repo, but it kind of went quiet. Now I hear about Test2::Suite which appears to be a duplicate/replacement for Test::Stream. I'm obviously not hanging out in the right places to know what the roadmap looks like.

If Test::Stream is a dead end could the repository be updated to say so?

**Comment by exodist** [comment]
Sorry. There has been intentional silence on this because it is not completely settled yet. Test-Stream is in fact a dead end, in favor of Test2/Test2::Suite. **However** Test2 is still not considered stable, so I can't recommend switching to it yet.

Ultimately what happened is the toolchain and perl-qa groups provided a lot of feedback on Test-Stream, much of which was necessary for it to make it into core. Unfortunately several of these things were things that could not be changed without breaking compatibility on Test-Stream, which was already marked stable. Further they demanded it be split into 2 parts, and be given a namespace restructuring.

Test2/Test2::Suite is the result of the feedback. It is Test-Stream split into 2 dists (3 if you count Test2-Workflow). But I am not going to announce it until I am sure it is done changing, and QA/toolchain have had a chance to review it.

So, if you want the new features and capabilities right now then you should continue to use Test::Stream. When Test2 becomes stable I will make a formal announcement, and add docs for converting from Test-Stream to Test2. Test-Stream itself will not be removed from cpan, nor will I break backcompat on it, so it is perfectly fine to keep using it, however it will not get any new features or capabilities, and it will not be possible to combine Test-Stream and Test2 tools, the differences (mostly due to feedback) are too severe.

**Comment by mlawren** [comment]
On Tue Feb 02, 2016 at 07:43:05AM -0800, Chad Granum wrote:
> Sorry. There has been intentional silence on this because it is not
> completely settled yet. Test-Stream is in fact a dead end, in favor

If that much is known then it should at least be documented in
Test-Stream to prevent new users from picking it up for new projects or
progressing further along that path.

Thanks for taking the time to write the rest of the story. From the
outside of the whole discussion I'm really happy about the whole
Stream/Test2/Suite development. It feels like a complete, modern
testing system. Looking forward to relying on it when it stabilises.

-- 
Mark Lawrence

**Comment by mlawren** [comment]
In the meantime there has been plenty of posts and information and development on Test2, to the point where (at least in my mind) Test::Stream has all but fallen out of consciousness. As there is now a DEPRECATED message in the repo and READMEs then I'll close this issue to keep my issue list clean.
